### PR TITLE
Small refactor on States and Tests for Easier Code readability

### PR DESCRIPTION
**Pull request by kanake10**
This PR adds the following functionality to this repo:

- create one sealed UIState (AllStatesUtil) to avoid multiple data classes in every Viewmodel/fragment/activity . 
- Inherit values created in AllStatesUtil in respective functions in Viewmodel/fragment/activity.
- Add the missing category parameter in MovieEntityDetailsViewModelTest for the test to pass.
- Refactor all values with initial UiState in viewmodel tests to AllStatesUtil class to ensure tests pass
- Create constants in various classes to avoid hardcoded strings in the repo.
- Create a base dao to remove boilerplate code in db.
- rename model classes with suffix that fit them in their respective modules to easily read the code (eg a model class supposed to be an entity to end with suffix entity)
- rename model classes with suffix that fit them in their respective modules to easily read the code (eg a model class supposed to be an entity to end with suffix entity)
- Create one sealed Navigation State which shall be inherited in needed functions.
Screenshot 2022-11-23 at 21 16 26

### CODE REVIEW

**Comment by kanake10** [comment]
> @kanake10 Thank you for the collaboration, much appreciated.
> 
> It's a quite big PR; it would be better to have more targeted smaller PRs.
> 
> Having said that, I would really like to know more about the decisions you have made in this PR are you following any conventions?
> 
> You have mentioned:
> 
> > rename model classes with suffix that fit them in their respective modules to easily read the code
> 
> The current code base's entity names do not have any suffixes in the presentation layer, but they do in the data layer and domain layer. The domain layer uses the suffix "entity," whereas the data layer uses the suffix "data."
> 
> Once we got familiar with the convention, It would be easier to read and understand.



> @kanake10 Thank you for the collaboration, much appreciated.
> 
> It's a quite big PR; it would be better to have more targeted smaller PRs.
> 
> Having said that, I would really like to know more about the decisions you have made in this PR are you following any conventions?
> 
> You have mentioned:
> 
> > rename model classes with suffix that fit them in their respective modules to easily read the code
> 
> The current code base's entity names do not have any suffixes in the presentation layer, but they do in the data layer and domain layer. The domain layer uses the suffix "entity," whereas the data layer uses the suffix "data."
> 
> Once we got familiar with the convention, It would be easier to read and understand.



> @kanake10 Thank you for the collaboration, much appreciated.
> 
> It's a quite big PR; it would be better to have more targeted smaller PRs.
> 
> Having said that, I would really like to know more about the decisions you have made in this PR are you following any conventions?
> 
> You have mentioned:
> 
> > rename model classes with suffix that fit them in their respective modules to easily read the code
> 
> The current code base's entity names do not have any suffixes in the presentation layer, but they do in the data layer and domain layer. The domain layer uses the suffix "entity," whereas the data layer uses the suffix "data."
> 
> Once we got familiar with the convention, It would be easier to read and understand.

I renamed the different model classes using the following convention  eg:

-  Data class with @Entity annotations to end with the suffix "Entity"
- The data classes which is a response from the API to end with "Dto" suffix.
- Model classes in the domain module to end with "Model" suffix

**Comment by kanake10** [comment]
**Regarding the UIState:**

saw this concept was used in the [Now in android app](https://github.com/android/nowinandroid) repository to hold all the data that should be displayed on the screen.

[Implementation in the the now in android app](https://github.com/android/nowinandroid/blob/main/feature/foryou/src/main/java/com/google/samples/apps/nowinandroid/feature/foryou/OnboardingUiState.kt)



Basic Example of the sealed UIClass
WhatsApp Image 2022-11-24 at 23 43 16

**Comment by AliAsadi** [comment]
> I renamed the different model classes using the following convention eg:
> 
> Data class with https://github.com/entity annotations to end with the suffix "Entity"
> The data classe which is a response from the API to end with "Dto" suffix.
> Model classes in the domain module to end with "Model" suffix


Although it's great to learn about new ideas and conventions, for this project I'm going to stick with the my convention at least for now. It might change in the future, but for now,  I find it to be simpler to understand and follow.

**Comment by AliAsadi** [comment]
> Regarding the UIState:
> 
> saw this concept was used in the [Now in android app](https://github.com/android/nowinandroid) repository to hold all the data that should be displayed on the screen.
> 
> [Implementation in the the now in android app](https://github.com/android/nowinandroid/blob/main/feature/foryou/src/main/java/com/google/samples/apps/nowinandroid/feature/foryou/OnboardingUiState.kt)
> 
> Basic Example of the sealed UIClass

Yeah, nice!

In the project i tried to use various methods; the one you mentioned here is used in the FeedViewModel, while I followed the [Android Doc](https://developer.android.com/topic/architecture/ui-layer) when implemented the SearchViewModel.

**Comment by kanake10** [comment]
> 

Got it

**Pull request closed without merging**
